<Project Sdk="Godot.NET.Sdk/4.7.2">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <Nullable>enable</Nullable>
    <Version>1.0.14</Version>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Launcher\**\*.cs" />
    <Compile Remove="Updater\**\*.cs" />
    <Compile Remove="Core\**\*.cs" />
    <Compile Remove="Core.Tests\**\*.cs" />
    <ProjectReference Include="Core\Miniscuplter.Core.csproj" />
  </ItemGroup>
</Project>
