<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Miniscuplter.Launcher</AssemblyName>
    <RootNamespace>Miniscuplter.Launcher</RootNamespace>
    <Version>0.9.9</Version>
  </PropertyGroup>
</Project>
